<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Catalog.Application\Catalog.Application.csproj" />
    <ProjectReference Include="..\Catalog.Data\Catalog.Data.csproj" />
    <ProjectReference Include="..\Common.Providers\Common.Providers.csproj" />
  </ItemGroup>
</Project>
