<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.*" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.*" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.*" />
    <PackageReference Include="AWSSDK.SQS" Version="4.*" />
    <PackageReference Include="Npgsql" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Lib\Common.Lib.csproj" />
    <ProjectReference Include="..\Common.Providers\Common.Providers.csproj" />
    <ProjectReference Include="..\Tenancy.Application\Tenancy.Application.csproj" />
    <ProjectReference Include="..\Tenancy.Data\Tenancy.Data.csproj" />
  </ItemGroup>
</Project>
