<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Catalog.Application\Catalog.Application.csproj" />
    <ProjectReference Include="..\Catalog.Data\Catalog.Data.csproj" />
    <ProjectReference Include="..\Common.Providers\Common.Providers.csproj" />
  </ItemGroup>
</Project>
