<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.*" />
    <PackageReference Include="Npgsql" Version="10.0.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Database\Common.Database.csproj" />
    <ProjectReference Include="..\Common.Lib\Common.Lib.csproj" />
    <ProjectReference Include="..\Tenancy.Application\Tenancy.Application.csproj" />
  </ItemGroup>
</Project>
