<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Orders.Domain\Orders.Domain.csproj" />
    <ProjectReference Include="..\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\Common.Lib\Common.Lib.csproj" />
  </ItemGroup>
</Project>
